---
params:
  baseURL: https://all64bits.github.io
  homeInfoParams:
    Title: Welcome. I'm Mike
    Content: |
      This is a blog, but it's also kind of a wiki. A... bliki.
      A wik...og.
  # ShowShareButtons: true
  ShowReadingTime: true
  ShowFullTextinRSS: true
  # ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  editPost:
    URL: "https://gitlab.com/all64bits/zettlekasten/"
    Text: "Suggest Changes"
    appendFilePath: true  # to append file path to Edit link
  socialIcons:
    - name: keybase
      url: https://keybase.io/all64bits
    - name: lastfm
      url: https://www.last.fm/user/all64bits

menu:
  main:
    - identifier: about
      name: about
      url: /3
      weight: 20
    - identifier: search
      name: search
      url: /search
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: homepage
      name: home
      url: /index.html/
      weight: 30

outputs:
  home:
    - HTML
    - RSS
    - JSON
